version: '3.8'
services:
  karaoke-web:
    build: .
    container_name: karaoke-web
    restart: unless-stopped
    ports:
      - "8085:8000"
    volumes:
      # บน Unraid ให้เปลี่ยนเป็น path บน Cache เช่น /mnt/user/appdata/karaoke/storage
      - /mnt/cache/appdata/karaoke-web/storage:/app/storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1
